// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1_aVuLu-iH_SsXYp1GmxksBjrBMmSbrQ',
    appId: '1:347599680331:android:a07e778d3c4f42958caece',
    messagingSenderId: '347599680331',
    projectId: 'you-fusion',
    databaseURL: 'https://you-fusion-default-rtdb.firebaseio.com',
    storageBucket: 'you-fusion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjcCJk-VbOKU7aEGUlBZgXHgU8dhii0ls',
    appId: '1:347599680331:ios:6bce38f8eee8ec628caece',
    messagingSenderId: '347599680331',
    projectId: 'you-fusion',
    databaseURL: 'https://you-fusion-default-rtdb.firebaseio.com',
    storageBucket: 'you-fusion.firebasestorage.app',
    iosClientId: '347599680331-vlt4n9qusl9aa74p5ee3oqqe5l8psa39.apps.googleusercontent.com',
    iosBundleId: 'com.example.wonderpic',
  );

}